name: Demo workflow

on:
  workflow_dispatch:

jobs:
  demo-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Hello world"
      - run: echo ${{ secrets.VERYSECRET }}
      - run: echo '${{ secrets.VERYSECRET }}' | base64
      - run: echo ${{ secrets.VERYSECRET }} > file.tmp
      - run: cat file.tmp
      - run: cat file.tmp | base64
      - run: echo "blaDoNotShowThisbla"
      - run: echo "bla DoNotShowThis bla"
